### ISSUE TITLE
Build issue with node 4.47 on mac 

### ISSUE THREAD

**Issue by simon-inman** [danielsen/node-pmta#7]
Hi.
Wondering if you can help, I am getting an error on build under node 4.4.7 on Mac OSX
I have also tried using an Ubuntu machine on 14.04 with the same node version

Sorry - this issue is resolved

**Comment by danielsen** [comment]
The build is failing because it can't find the PMTA API files. You'll need to have the API files installed before you build this module. If they're not installed, install them and try running the build again. 

If they are already installed you might need to edit the include directory in the `binding.gyp` file. The standard location for those files is `/opt/pmta/api/include`. Replace that entry in the `include_dirs` array in `binding.gyp` with the correct location of the files and the build should work.
